$ErrorActionPreference = "Stop"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { throw "Docker is not installed or not on PATH." }
docker info *> $null
if ($LASTEXITCODE -ne 0) { throw "Docker Desktop is installed but not running." }
docker compose version

if (-not (Test-Path ".env")) {
    Copy-Item ".env.example" ".env"
    $password = [guid]::NewGuid().ToString("N")
    (Get-Content ".env") -replace 'CHANGE_ME_AUTOGENERATED_BY_BOOTSTRAP', $password | Set-Content ".env" -Encoding ascii
    Write-Host "Created .env with a random local-only database password."
}

Write-Host "Pulling/building development containers..."
docker compose pull db
docker compose build tooling

Write-Host "Starting PostGIS..."
docker compose up -d db
& .\scripts\db-wait.ps1

Write-Host "Applying/checking migrations..."
& .\scripts\db-migrate.ps1

Write-Host "Running schema and Python tests..."
& .\scripts\db-test-schema.ps1
& .\scripts\verify-release.ps1
& .\scripts\test-python.ps1
& .\scripts\dry-run-v061.ps1

Write-Host "Importing canonical v0.6.1 into the LOCAL development database..."
& .\scripts\import-v061.ps1
& .\scripts\db-test-v061.ps1
& .\scripts\db-test-non-atlantic.ps1

Write-Host "Creating a local validation backup..."
& .\scripts\backup-db.ps1

Write-Host "Development environment is ready. The local database remains NON-CANONICAL."
