$ErrorActionPreference = "Stop"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { throw "Docker is not installed or not on PATH." }
docker info *> $null
if ($LASTEXITCODE -ne 0) { throw "Docker Desktop is installed but not running." }
docker compose version

if (-not (Test-Path ".env")) {
    Copy-Item ".env.example" ".env"
    $password = [guid]::NewGuid().ToString("N")
    (Get-Content ".env") -replace 'CHANGE_ME_AUTOGENERATED_BY_BOOTSTRAP', $password | Set-Content ".env" -Encoding ascii
    Write-Host "Created .env with a random local-only database password."
}

Write-Host "Pulling/building development containers..."
docker compose pull db
docker compose build tooling

Write-Host "Starting PostGIS..."
docker compose up -d db
& .\scripts\db-wait.ps1

Write-Host "Applying/checking migrations and foundation tests..."
& .\scripts\db-migrate.ps1
& .\scripts\db-test-schema.ps1
& .\scripts\test-python.ps1
& .\scripts\db-test-non-atlantic.ps1
& .\scripts\db-test-release-reconstruction.ps1

$workbook = "data/releases/v0.6.1/Historical_Slavery_Atlas_v0.6.1_Controlled_Atlantic_Ingestion.xlsx"
if (Test-Path $workbook) {
    Write-Host "Canonical release artifact found; running release-specific validation..."
    & .\scripts\verify-release.ps1
    & .\scripts\dry-run-v061.ps1
    & .\scripts\import-v061.ps1
    & .\scripts\db-test-v061.ps1
} else {
    Write-Host "Canonical v0.6.1 binary is not present. Core development environment is valid; release-import validation was explicitly skipped."
}

Write-Host "Creating a local validation backup..."
& .\scripts\backup-db.ps1
Write-Host "Development environment is ready. The local database remains NON-CANONICAL."
