#!/usr/bin/env bash
set -euo pipefail
command -v docker >/dev/null || { echo "Docker is not installed." >&2; exit 1; }
docker info >/dev/null
if [[ ! -f .env ]]; then
  cp .env.example .env
  password="$(docker run --rm alpine:3.22 sh -c "cat /proc/sys/kernel/random/uuid | tr -d '-'")"
  sed -i.bak "s/CHANGE_ME_AUTOGENERATED_BY_BOOTSTRAP/$password/" .env && rm -f .env.bak
  echo "Created .env with a random local-only database password."
fi
docker compose pull db
docker compose build tooling
docker compose up -d db
./scripts/db-wait.sh
./scripts/db-migrate.sh
./scripts/db-test-schema.sh
./scripts/verify-release.sh
./scripts/test-python.sh
./scripts/dry-run-v061.sh
./scripts/import-v061.sh
./scripts/db-test-v061.sh
./scripts/db-test-non-atlantic.sh
./scripts/backup-db.sh
echo "Development environment is ready. The local database remains NON-CANONICAL."
